import type { NextPage } from 'next';
import Head from 'next/head';
import Shell from '../../components/AppShell';

import ReadingComponent from '../../components/Pages/Reading';

const Reading: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Reading</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Shell>
				<ReadingComponent />
			</Shell>
		</div>
	);
};

export default Reading;
