import type { NextPage } from 'next';
import Head from 'next/head';

import { Text } from '@mantine/core';

import Shell from '../components/AppShell';
import Link from 'next/link';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Shell>
				<div className="w-full lg:pl-[15%] lg:pt-[3%] xs:px-[20px] xs:pt-[50px]">
					<Text size="xl">Welcome to book store</Text>
					<Text size="md">This is recruit task</Text>
					<Text size="sm" color={'cyan'}>
						Piotr Gałka -
						https://github.com/Piotrek-hub/recruit-task
					</Text>
					<Link href="/books">
						<Text underline className="cursor-pointer">
							/books
						</Text>
					</Link>
					<Link href="/favorites">
						<Text underline className="cursor-pointer">
							/favorites
						</Text>
					</Link>
				</div>
			</Shell>
		</div>
	);
};

export default Home;
