import type { NextPage } from 'next';
import Head from 'next/head';
import Shell from '../../components/AppShell';

import BooksComponent from '../../components/Pages/Books';

const Books: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Books</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Shell>
				<BooksComponent />
			</Shell>
		</div>
	);
};

export default Books;
